<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#e85811" />

    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link rel="shortcut icon" href="./img/Logo.svg" type="image/x-icon">

    <title>B2M TOMBOLA</title>

    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/fontawesome.css">
    <link rel="stylesheet" href="css/<?= "$page.css" ?>">
</head>

<body id="main">
    <?php include $main_content; ?>
</body>

<script type="module" src="js/<?= "$page.js" ?>"></script>

</html>